### ISSUE TITLE
Provide arch linux aura package:)

### ISSUE THREAD

**Issue by sluedecke** [blippy/neoleo#1]
Hi blippy, I would like to use oleo on arch linux, but the aura package https://aur.archlinux.org/packages/oleo/ is broken.  Can you be so kind and provide one for noleo?

**Comment by blippy** [comment]
I would be delighted to!

Do you mean "AUR", the standard package manager, or "aura", an Arch package manager written in Haskell? I have written for netiher, so you might need to bear with me, as I work out how it's done.

It is probably worth my while releasing a new version of neoleo so that you have all the latest goodies.

Do you want just a curses interface, an X interface, or the grandest of them all, the Motif interface? The Motif interface can be done, but there's a snag: it requires xbae. xbae is available in AUR, but it has openmotif as a dependency. This is unfortunate, as openmotif conflicts with lesstif. lesstif is required by more packages. So there's something of a Catch-22 situation.

How keen are you on the Motif interface? The most expedient way of getting it up-and-running is to compile and install xbae from sources yourself. 

neoleo always has the ncurses interface available, and if Motif is not available, it will fallback to an X11 interface if the appropriate headers are available. The X11 interface looks mostly like the ncurses one, but with the nice advantage that the mouse works.

Let me know your thoughts.

**Comment by blippy** [comment]
AUR package here: https://aur.archlinux.org/packages/neoleo/  with a recent release.

**Comment by sluedecke** [comment]
works fine, thank you very much for providing it!
