### ISSUE TITLE
io-utils.cc:1002:10: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]

### ISSUE THREAD

**Issue by stefanhusmann** [blippy/neoleo#44]
Under Arch Linux using g++ 10.1.0 and the environment variable LANG=C the compilation fails with an overflow.

[buildlog.txt](https://github.com/blippy/neoleo/files/4841276/buildlog.txt)

Strangely the overflow also appears if I use the german language localization, but the values are different.

[buildlog_german.txt](https://github.com/blippy/neoleo/files/4841278/buildlog_german.txt)

**Comment by blippy** [comment]
The following commit:
https://github.com/blippy/neoleo/commit/313aa68aa756194c0d91c7bb40bcd23b92dc3c20
allows for the reproduction of the error on Arch Linux as it stands.

To reproduce the compilation error:
```
./configure --with-fortify
```

The problem appears to occur when you combine g++ compilation options `-O2` with `-D_FORTIFY_SOURCE=2` rather than `-O`. It does not appear to be related to the `LANG` settings. 

I tried compiling `--with-fortify` on Ubuntu 20.04 with g++ version 9.3.0, and obtained a clean build. The problem manifests on Arch Linux with g++ version 10.1.0. (Grr, so many corner cases!).

At least I can reproduce the compilation problem now. I will investigate further.

**Comment by blippy** [comment]
The latest commits should now fix the build problems. I basically rewrote `col_to_str()` in a more C++-like way.

Please confirm that a re-compile now works for you.

**Comment by stefanhusmann** [comment]
Thanks, works fine here!
